# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

development:
  secret_key_base: 13c4a4da3cab634fc8b580dc4bfcd1f06dd128e6823a4a49c0d3f5922042bcca1f4cae73b82b17481367425cf62e15ae4c64d1586824a039fb63ecdf262f69da

test:
  secret_key_base: 43d818cebab9ac9fad6dc83b29d662cd6c5d68ab9367d097cd9e7e03e5ee84a82190ff49ab01c89bb3f491569e84bb68545f9405ec80d6e9206e6a8beb343ce8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
